/**
 * Super Admin platform settings — frontend-only dummy state (future /admin APIs).
 */
import { useCallback, useState } from 'react';
import { useTranslation } from 'react-i18next';
import toast from 'react-hot-toast';
import {
  AlertTriangle,
  Bell,
  Building2,
  ClipboardList,
  CreditCard,
  FileText,
  Globe2,
  HardDrive,
  Lock,
  Save,
  ScrollText,
  Undo2,
} from 'lucide-react';
import '../styles/SuperAdminSettings.css';

const NOTIFICATION_EVENT_KEYS = [
  'evNewReg',
  'evApproved',
  'evRejected',
  'evMoreInfo',
  'evPwdReset',
  'evOverdue',
  'evPayment',
  'evSuspended',
  'evDoc',
];

const CHANNEL_KEYS = ['email', 'sms', 'whatsapp', 'push'];

const CHANNEL_LABEL_KEYS = {
  email: 'chEmail',
  sms: 'chSms',
  whatsapp: 'chWa',
  push: 'chPush',
};

function buildDefaultNotifications() {
  const o = {};
  NOTIFICATION_EVENT_KEYS.forEach((e) => {
    o[e] = { email: true, sms: false, whatsapp: false, push: false };
  });
  return o;
}

function createInitialSettings() {
  return {
    platform: {
      name: 'EquiCore',
      logoFileName: '',
      supportEmail: 'support@equicore.example',
      supportPhone: '+973 0000 0000',
      company: 'EquiCore Technologies W.L.L.',
      country: 'Bahrain',
      currency: 'BHD',
      language: 'en',
      timezone: 'Asia/Bahrain',
    },
    registration: {
      selfReg: true,
      requireApproval: true,
      requireCommercial: true,
      requireDocs: true,
      reapply: true,
      expireDays: 30,
      priority: 'normal',
    },
    subscription: {
      enabled: true,
      plan3: true,
      plan6: true,
      planYear: true,
      price3: '299',
      price6: '549',
      priceYear: '999',
      graceDays: 7,
      autoSuspend: true,
      payCash: true,
      payBenefit: true,
      payCard: true,
      payBank: true,
      payCheque: false,
      payOther: false,
    },
    access: {
      suspendStable: true,
      blockUsers: true,
      ownerPwdReset: true,
      tempPwd: false,
      sessionTimeout: 45,
      lockout: 5,
      twoFa: false,
    },
    notifications: buildDefaultNotifications(),
    reports: {
      pdfEnabled: true,
      defaultLang: 'en',
      includeLogo: true,
      includeSignature: true,
      pageNumbers: true,
      footer: 'Generated by EquiCore — Confidential',
      rtl: true,
      format: 'A4',
    },
    localization: {
      langEn: true,
      langAr: true,
      rtl: true,
      themeLight: true,
      themeDark: false,
      themeSystem: false,
      dateFormat: 'YYYY-MM-DD',
      timeFormat: '24h',
      currencyFormat: 'BHD 0.000',
    },
    backup: {
      scheduled: false,
      frequency: 'daily',
      lastBackup: '2026-05-20',
      retention: 365,
    },
    dangerFlags: {
      registrationsDisabled: false,
      maintenanceMode: false,
    },
  };
}

const INITIAL_AUDIT_LOGS = [
  {
    id: '1',
    date: '2026-05-24 09:12',
    admin: 'super.admin@equicore',
    action: 'Approved stable',
    module: 'StableRequests',
    stable: 'Al Najm Stables',
    status: 'Success',
  },
  {
    id: '2',
    date: '2026-05-23 16:40',
    admin: 'super.admin@equicore',
    action: 'Updated subscription',
    module: 'Subscriptions',
    stable: 'Oasis Equestrian',
    status: 'Success',
  },
  {
    id: '3',
    date: '2026-05-22 11:05',
    admin: 'ops@equicore',
    action: 'Password reset issued',
    module: 'Users',
    stable: '—',
    status: 'Pending',
  },
];

const NAV = [
  { id: 'platform', icon: Building2 },
  { id: 'registration', icon: ClipboardList },
  { id: 'subscription', icon: CreditCard },
  { id: 'access', icon: Lock },
  { id: 'notifications', icon: Bell },
  { id: 'reports', icon: FileText },
  { id: 'localization', icon: Globe2 },
  { id: 'audit', icon: ScrollText },
  { id: 'backup', icon: HardDrive },
  { id: 'danger', icon: AlertTriangle },
];

function ConfirmModal({ open, title, description, onClose, onConfirm, confirmLabel, cancelLabel }) {
  if (!open) return null;
  return (
    <div className="super-admin-settings-page__modal-overlay" role="presentation" onClick={onClose}>
      <div
        className="super-admin-settings-page__modal"
        role="dialog"
        aria-modal="true"
        onClick={(e) => e.stopPropagation()}
      >
        <h3>{title}</h3>
        <p>{description}</p>
        <div className="super-admin-settings-page__modal-actions">
          <button type="button" className="super-admin-settings-page__btn super-admin-settings-page__btn--ghost" onClick={onClose}>
            {cancelLabel}
          </button>
          <button
            type="button"
            className="super-admin-settings-page__btn super-admin-settings-page__btn--gold"
            onClick={() => {
              onConfirm();
              onClose();
            }}
          >
            {confirmLabel}
          </button>
        </div>
      </div>
    </div>
  );
}

export default function SuperAdminSettings() {
  const { t, i18n } = useTranslation();
  const tr = useCallback((key) => t(`pages.superAdminSettings.${key}`), [t]);
  const pageRtl = i18n.language?.startsWith('ar');

  const [activeSection, setActiveSection] = useState('platform');
  const [settings, setSettings] = useState(() => createInitialSettings());
  const [auditLogs, setAuditLogs] = useState(() => [...INITIAL_AUDIT_LOGS]);

  const [modal, setModal] = useState({
    open: false,
    title: '',
    description: '',
    onConfirm: () => {},
  });

  const openModal = useCallback((title, description, onConfirm) => {
    setModal({ open: true, title, description, onConfirm });
  }, []);

  const closeModal = useCallback(() => {
    setModal((m) => ({ ...m, open: false }));
  }, []);

  const patch = useCallback((section, partial) => {
    setSettings((s) => ({ ...s, [section]: { ...s[section], ...partial } }));
  }, []);

  const patchNotif = useCallback((eventKey, channel, value) => {
    setSettings((s) => ({
      ...s,
      notifications: {
        ...s.notifications,
        [eventKey]: { ...s.notifications[eventKey], [channel]: value },
      },
    }));
  }, []);

  const handleSave = () => {
    toast.success(tr('toasts.saved'));
  };

  const handleReset = () => {
    setSettings(createInitialSettings());
    setAuditLogs([...INITIAL_AUDIT_LOGS]);
    toast.success(tr('toasts.reset'));
  };

  const handleLogo = (e) => {
    const f = e.target.files?.[0];
    if (f) {
      patch('platform', { logoFileName: f.name });
      toast.success(tr('toasts.logoSelected'));
    }
  };

  const sectionCard = (headingKey, icon, children, danger = false) => (
    <section className={`super-admin-settings-page__card${danger ? ' super-admin-settings-page__card--danger' : ''}`}>
      <h2>
        {icon}
        {t(`pages.superAdminSettings.${headingKey}.heading`)}
      </h2>
      {children}
    </section>
  );

  const ToggleRow = ({ section, field, labelKey }) => (
    <div className="super-admin-settings-page__toggle-row">
      <span>{t(`pages.superAdminSettings.${section}.${labelKey}`)}</span>
      <label className="super-admin-settings-page__switch">
        <input
          type="checkbox"
          checked={settings[section][field]}
          onChange={(e) => patch(section, { [field]: e.target.checked })}
        />
        <span className="super-admin-settings-page__switch-slider" />
      </label>
    </div>
  );

  const renderPlatform = () =>
    sectionCard(
      'platform',
      <Building2 className="super-admin-settings-page__nav-icon" size={18} aria-hidden />,
      <>
        <div className="super-admin-settings-page__grid">
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.platform.name')}</span>
            <input type="text" value={settings.platform.name} onChange={(e) => patch('platform', { name: e.target.value })} />
          </label>
          <div className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.platform.logo')}</span>
            <p className="super-admin-settings-page__card-lead" style={{ margin: '0 0 0.35rem' }}>
              {t('pages.superAdminSettings.platform.logoHint')}
            </p>
            <label className="super-admin-settings-page__btn super-admin-settings-page__btn--ghost super-admin-settings-page__file">
              <input type="file" accept=".png,.svg,.jpg,.jpeg" hidden onChange={handleLogo} />
              {t('pages.superAdminSettings.platform.chooseFile')}
              {settings.platform.logoFileName ? ` — ${settings.platform.logoFileName}` : ''}
            </label>
          </div>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.platform.supportEmail')}</span>
            <input
              type="email"
              value={settings.platform.supportEmail}
              onChange={(e) => patch('platform', { supportEmail: e.target.value })}
            />
          </label>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.platform.supportPhone')}</span>
            <input
              type="tel"
              value={settings.platform.supportPhone}
              onChange={(e) => patch('platform', { supportPhone: e.target.value })}
            />
          </label>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.platform.company')}</span>
            <input type="text" value={settings.platform.company} onChange={(e) => patch('platform', { company: e.target.value })} />
          </label>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.platform.country')}</span>
            <input type="text" value={settings.platform.country} onChange={(e) => patch('platform', { country: e.target.value })} />
          </label>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.platform.currency')}</span>
            <select value={settings.platform.currency} onChange={(e) => patch('platform', { currency: e.target.value })}>
              <option value="BHD">BHD</option>
              <option value="AED">AED</option>
              <option value="SAR">SAR</option>
              <option value="USD">USD</option>
            </select>
          </label>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.platform.language')}</span>
            <select value={settings.platform.language} onChange={(e) => patch('platform', { language: e.target.value })}>
              <option value="en">English</option>
              <option value="ar">العربية</option>
            </select>
          </label>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.platform.timezone')}</span>
            <select value={settings.platform.timezone} onChange={(e) => patch('platform', { timezone: e.target.value })}>
              <option value="Asia/Bahrain">Asia/Bahrain</option>
              <option value="Asia/Dubai">Asia/Dubai</option>
              <option value="Asia/Riyadh">Asia/Riyadh</option>
              <option value="UTC">UTC</option>
            </select>
          </label>
        </div>
      </>
    );

  const renderRegistration = () =>
    sectionCard(
      'registration',
      <ClipboardList className="super-admin-settings-page__nav-icon" size={18} aria-hidden />,
      <>
        <ToggleRow section="registration" field="selfReg" labelKey="selfReg" />
        <ToggleRow section="registration" field="requireApproval" labelKey="requireApproval" />
        <ToggleRow section="registration" field="requireCommercial" labelKey="requireCommercial" />
        <ToggleRow section="registration" field="requireDocs" labelKey="requireDocs" />
        <ToggleRow section="registration" field="reapply" labelKey="reapply" />
        <div className="super-admin-settings-page__grid" style={{ marginTop: '0.75rem' }}>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.registration.expireDays')}</span>
            <input
              type="number"
              min={1}
              max={365}
              value={settings.registration.expireDays}
              onChange={(e) => patch('registration', { expireDays: Number(e.target.value) || 1 })}
            />
          </label>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.registration.priority')}</span>
            <select value={settings.registration.priority} onChange={(e) => patch('registration', { priority: e.target.value })}>
              <option value="low">{t('pages.superAdminSettings.registration.priorityLow')}</option>
              <option value="normal">{t('pages.superAdminSettings.registration.priorityNormal')}</option>
              <option value="high">{t('pages.superAdminSettings.registration.priorityHigh')}</option>
            </select>
          </label>
        </div>
      </>
    );

  const renderSubscription = () =>
    sectionCard(
      'subscription',
      <CreditCard className="super-admin-settings-page__nav-icon" size={18} aria-hidden />,
      <>
        <ToggleRow section="subscription" field="enabled" labelKey="enabled" />
        <p className="super-admin-settings-page__card-lead">{t('pages.superAdminSettings.subscription.plansTitle')}</p>
        <div className="super-admin-settings-page__check-grid">
          <label className="super-admin-settings-page__check">
            <input type="checkbox" checked={settings.subscription.plan3} onChange={(e) => patch('subscription', { plan3: e.target.checked })} />
            {t('pages.superAdminSettings.subscription.plan3')}
          </label>
          <label className="super-admin-settings-page__check">
            <input type="checkbox" checked={settings.subscription.plan6} onChange={(e) => patch('subscription', { plan6: e.target.checked })} />
            {t('pages.superAdminSettings.subscription.plan6')}
          </label>
          <label className="super-admin-settings-page__check">
            <input
              type="checkbox"
              checked={settings.subscription.planYear}
              onChange={(e) => patch('subscription', { planYear: e.target.checked })}
            />
            {t('pages.superAdminSettings.subscription.planYear')}
          </label>
        </div>
        <div className="super-admin-settings-page__grid" style={{ marginTop: '0.75rem' }}>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.subscription.price3')}</span>
            <input type="text" value={settings.subscription.price3} onChange={(e) => patch('subscription', { price3: e.target.value })} />
          </label>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.subscription.price6')}</span>
            <input type="text" value={settings.subscription.price6} onChange={(e) => patch('subscription', { price6: e.target.value })} />
          </label>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.subscription.priceYear')}</span>
            <input
              type="text"
              value={settings.subscription.priceYear}
              onChange={(e) => patch('subscription', { priceYear: e.target.value })}
            />
          </label>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.subscription.grace')}</span>
            <input
              type="number"
              min={0}
              value={settings.subscription.graceDays}
              onChange={(e) => patch('subscription', { graceDays: Number(e.target.value) || 0 })}
            />
          </label>
        </div>
        <ToggleRow section="subscription" field="autoSuspend" labelKey="autoSuspend" />
        <p className="super-admin-settings-page__card-lead">{t('pages.superAdminSettings.subscription.payTitle')}</p>
        <div className="super-admin-settings-page__check-grid">
          {[
            ['payCash', 'payCash'],
            ['payBenefit', 'payBenefit'],
            ['payCard', 'payCard'],
            ['payBank', 'payBank'],
            ['payCheque', 'payCheque'],
            ['payOther', 'payOther'],
          ].map(([field, lk]) => (
            <label key={field} className="super-admin-settings-page__check">
              <input
                type="checkbox"
                checked={settings.subscription[field]}
                onChange={(e) => patch('subscription', { [field]: e.target.checked })}
              />
              {t(`pages.superAdminSettings.subscription.${lk}`)}
            </label>
          ))}
        </div>
      </>
    );

  const renderAccess = () =>
    sectionCard(
      'access',
      <Lock className="super-admin-settings-page__nav-icon" size={18} aria-hidden />,
      <>
        <ToggleRow section="access" field="suspendStable" labelKey="suspendStable" />
        <ToggleRow section="access" field="blockUsers" labelKey="blockUsers" />
        <ToggleRow section="access" field="ownerPwdReset" labelKey="ownerPwdReset" />
        <ToggleRow section="access" field="tempPwd" labelKey="tempPwd" />
        <div className="super-admin-settings-page__grid" style={{ marginTop: '0.75rem' }}>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.access.sessionTimeout')}</span>
            <input
              type="number"
              min={5}
              value={settings.access.sessionTimeout}
              onChange={(e) => patch('access', { sessionTimeout: Number(e.target.value) || 5 })}
            />
          </label>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.access.lockout')}</span>
            <input type="number" min={1} value={settings.access.lockout} onChange={(e) => patch('access', { lockout: Number(e.target.value) || 1 })} />
          </label>
        </div>
        <ToggleRow section="access" field="twoFa" labelKey="twoFa" />
      </>
    );

  const renderNotifications = () =>
    sectionCard(
      'notifications',
      <Bell className="super-admin-settings-page__nav-icon" size={18} aria-hidden />,
      <>
        <p className="super-admin-settings-page__card-lead">{t('pages.superAdminSettings.notifications.channels')}</p>
        <p className="super-admin-settings-page__card-lead" style={{ marginTop: '-0.35rem' }}>
          {t('pages.superAdminSettings.notifications.events')}
        </p>
        <div className="super-admin-settings-page__notif-grid">
          <div />
          {CHANNEL_KEYS.map((ch) => (
            <div key={ch} className="super-admin-settings-page__notif-head">
              {t(`pages.superAdminSettings.notifications.${CHANNEL_LABEL_KEYS[ch]}`)}
            </div>
          ))}
          {NOTIFICATION_EVENT_KEYS.map((ev) => (
            <div key={ev} style={{ display: 'contents' }}>
              <div className="super-admin-settings-page__notif-event">{t(`pages.superAdminSettings.notifications.${ev}`)}</div>
              {CHANNEL_KEYS.map((ch) => (
                <div key={`${ev}-${ch}`} className="super-admin-settings-page__notif-cell">
                  <input
                    type="checkbox"
                    checked={settings.notifications[ev][ch]}
                    onChange={(e) => patchNotif(ev, ch, e.target.checked)}
                    aria-label={`${ev}-${ch}`}
                  />
                </div>
              ))}
            </div>
          ))}
        </div>
      </>
    );

  const renderReports = () =>
    sectionCard(
      'reports',
      <FileText className="super-admin-settings-page__nav-icon" size={18} aria-hidden />,
      <>
        <ToggleRow section="reports" field="pdfEnabled" labelKey="pdfEnabled" />
        <div className="super-admin-settings-page__grid" style={{ marginTop: '0.5rem' }}>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.reports.defaultLang')}</span>
            <select value={settings.reports.defaultLang} onChange={(e) => patch('reports', { defaultLang: e.target.value })}>
              <option value="en">English</option>
              <option value="ar">العربية</option>
            </select>
          </label>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.reports.format')}</span>
            <select value={settings.reports.format} onChange={(e) => patch('reports', { format: e.target.value })}>
              <option value="A4">{t('pages.superAdminSettings.reports.formatA4')}</option>
            </select>
          </label>
        </div>
        <ToggleRow section="reports" field="includeLogo" labelKey="includeLogo" />
        <ToggleRow section="reports" field="includeSignature" labelKey="includeSignature" />
        <ToggleRow section="reports" field="pageNumbers" labelKey="pageNumbers" />
        <ToggleRow section="reports" field="rtl" labelKey="rtl" />
        <label className="super-admin-settings-page__field super-admin-settings-page__field--full" style={{ marginTop: '0.5rem' }}>
          <span>{t('pages.superAdminSettings.reports.footer')}</span>
          <textarea value={settings.reports.footer} onChange={(e) => patch('reports', { footer: e.target.value })} />
        </label>
      </>
    );

  const renderLocalization = () =>
    sectionCard(
      'localization',
      <Globe2 className="super-admin-settings-page__nav-icon" size={18} aria-hidden />,
      <>
        <div className="super-admin-settings-page__check-grid">
          <label className="super-admin-settings-page__check">
            <input type="checkbox" checked={settings.localization.langEn} onChange={(e) => patch('localization', { langEn: e.target.checked })} />
            {t('pages.superAdminSettings.localization.langEn')}
          </label>
          <label className="super-admin-settings-page__check">
            <input type="checkbox" checked={settings.localization.langAr} onChange={(e) => patch('localization', { langAr: e.target.checked })} />
            {t('pages.superAdminSettings.localization.langAr')}
          </label>
        </div>
        <ToggleRow section="localization" field="rtl" labelKey="rtl" />
        <p className="super-admin-settings-page__card-lead">{t('pages.superAdminSettings.localization.themeHeading')}</p>
        <div className="super-admin-settings-page__check-grid">
          <label className="super-admin-settings-page__check">
            <input
              type="radio"
              name="theme"
              checked={settings.localization.themeLight}
              onChange={() => patch('localization', { themeLight: true, themeDark: false, themeSystem: false })}
            />
            {t('pages.superAdminSettings.localization.themeLight')}
          </label>
          <label className="super-admin-settings-page__check">
            <input
              type="radio"
              name="theme"
              checked={settings.localization.themeDark}
              onChange={() => patch('localization', { themeLight: false, themeDark: true, themeSystem: false })}
            />
            {t('pages.superAdminSettings.localization.themeDark')}
          </label>
          <label className="super-admin-settings-page__check">
            <input
              type="radio"
              name="theme"
              checked={settings.localization.themeSystem}
              onChange={() => patch('localization', { themeLight: false, themeDark: false, themeSystem: true })}
            />
            {t('pages.superAdminSettings.localization.themeSystem')}
          </label>
        </div>
        <div className="super-admin-settings-page__grid" style={{ marginTop: '0.75rem' }}>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.localization.dateFormat')}</span>
            <input type="text" value={settings.localization.dateFormat} onChange={(e) => patch('localization', { dateFormat: e.target.value })} />
          </label>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.localization.timeFormat')}</span>
            <select value={settings.localization.timeFormat} onChange={(e) => patch('localization', { timeFormat: e.target.value })}>
              <option value="24h">24h</option>
              <option value="12h">12h</option>
            </select>
          </label>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.localization.currencyFormat')}</span>
            <input
              type="text"
              value={settings.localization.currencyFormat}
              onChange={(e) => patch('localization', { currencyFormat: e.target.value })}
            />
          </label>
        </div>
      </>
    );

  const renderAudit = () =>
    sectionCard(
      'audit',
      <ScrollText className="super-admin-settings-page__nav-icon" size={18} aria-hidden />,
      <>
        <div className="super-admin-settings-page__table-wrap">
          <table className="super-admin-settings-page__table">
            <thead>
              <tr>
                <th>{t('pages.superAdminSettings.audit.colDate')}</th>
                <th>{t('pages.superAdminSettings.audit.colAdmin')}</th>
                <th>{t('pages.superAdminSettings.audit.colAction')}</th>
                <th>{t('pages.superAdminSettings.audit.colModule')}</th>
                <th>{t('pages.superAdminSettings.audit.colStable')}</th>
                <th>{t('pages.superAdminSettings.audit.colStatus')}</th>
              </tr>
            </thead>
            <tbody>
              {auditLogs.length === 0 ? (
                <tr>
                  <td colSpan={6} style={{ textAlign: 'center', color: 'var(--color-gray-600)' }}>
                    {t('pages.superAdminSettings.audit.empty')}
                  </td>
                </tr>
              ) : (
                auditLogs.map((row) => (
                  <tr key={row.id}>
                    <td>{row.date}</td>
                    <td>{row.admin}</td>
                    <td>{row.action}</td>
                    <td>{row.module}</td>
                    <td>{row.stable}</td>
                    <td>{row.status}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
        <div className="super-admin-settings-page__row-actions">
          <button type="button" className="super-admin-settings-page__btn super-admin-settings-page__btn--ghost" onClick={() => toast.success(tr('toasts.exportLogs'))}>
            {t('pages.superAdminSettings.audit.export')}
          </button>
          <button
            type="button"
            className="super-admin-settings-page__btn super-admin-settings-page__btn--danger"
            onClick={() =>
              openModal(t('pages.superAdminSettings.audit.clear'), t('pages.superAdminSettings.audit.clearBody'), () => {
                setAuditLogs([]);
                toast.success(tr('toasts.cleared'));
              })
            }
          >
            {t('pages.superAdminSettings.audit.clear')}
          </button>
        </div>
      </>
    );

  const renderBackup = () =>
    sectionCard(
      'backup',
      <HardDrive className="super-admin-settings-page__nav-icon" size={18} aria-hidden />,
      <>
        <ToggleRow section="backup" field="scheduled" labelKey="scheduled" />
        <label className="super-admin-settings-page__field" style={{ marginTop: '0.5rem' }}>
          <span>{t('pages.superAdminSettings.backup.frequency')}</span>
          <select value={settings.backup.frequency} onChange={(e) => patch('backup', { frequency: e.target.value })}>
            <option value="daily">{t('pages.superAdminSettings.backup.freqDaily')}</option>
            <option value="weekly">{t('pages.superAdminSettings.backup.freqWeekly')}</option>
            <option value="monthly">{t('pages.superAdminSettings.backup.freqMonthly')}</option>
          </select>
        </label>
        <div className="super-admin-settings-page__grid" style={{ marginTop: '0.75rem' }}>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.backup.lastBackup')}</span>
            <input type="date" value={settings.backup.lastBackup} onChange={(e) => patch('backup', { lastBackup: e.target.value })} />
          </label>
          <label className="super-admin-settings-page__field">
            <span>{t('pages.superAdminSettings.backup.retention')}</span>
            <input type="number" min={30} value={settings.backup.retention} onChange={(e) => patch('backup', { retention: Number(e.target.value) || 30 })} />
          </label>
        </div>
        <div className="super-admin-settings-page__row-actions">
          <button type="button" className="super-admin-settings-page__btn super-admin-settings-page__btn--ghost" onClick={() => toast.success(tr('toasts.exportLogs'))}>
            {t('pages.superAdminSettings.backup.exportTenants')}
          </button>
          <button type="button" className="super-admin-settings-page__btn super-admin-settings-page__btn--ghost" onClick={() => toast.success(tr('toasts.exportLogs'))}>
            {t('pages.superAdminSettings.backup.exportSubs')}
          </button>
          <button type="button" className="super-admin-settings-page__btn super-admin-settings-page__btn--ghost" onClick={() => toast.success(tr('toasts.exportLogs'))}>
            {t('pages.superAdminSettings.backup.exportRequests')}
          </button>
        </div>
      </>
    );

  const renderDanger = () =>
    sectionCard(
      'danger',
      <AlertTriangle className="super-admin-settings-page__nav-icon" size={18} aria-hidden />,
      <>
        <p className="super-admin-settings-page__card-lead">{t('pages.superAdminSettings.danger.lead')}</p>
        <div className="super-admin-settings-page__row-actions">
          <button
            type="button"
            className="super-admin-settings-page__btn super-admin-settings-page__btn--danger"
            onClick={() =>
              openModal(t('pages.superAdminSettings.danger.disableReg'), t('pages.superAdminSettings.danger.disableRegBody'), () => {
                patch('dangerFlags', { registrationsDisabled: true });
                toast.success(tr('toasts.dangerDone'));
              })
            }
          >
            {t('pages.superAdminSettings.danger.disableReg')}
          </button>
          <button
            type="button"
            className="super-admin-settings-page__btn super-admin-settings-page__btn--danger"
            onClick={() =>
              openModal(t('pages.superAdminSettings.danger.suspendOverdue'), t('pages.superAdminSettings.danger.suspendOverdueBody'), () => {
                toast.success(tr('toasts.dangerDone'));
              })
            }
          >
            {t('pages.superAdminSettings.danger.suspendOverdue')}
          </button>
          <button
            type="button"
            className="super-admin-settings-page__btn super-admin-settings-page__btn--danger"
            onClick={() =>
              openModal(t('pages.superAdminSettings.danger.resetPlatform'), t('pages.superAdminSettings.danger.resetPlatformBody'), () => {
                toast.success(tr('toasts.dangerDone'));
              })
            }
          >
            {t('pages.superAdminSettings.danger.resetPlatform')}
          </button>
          <button
            type="button"
            className="super-admin-settings-page__btn super-admin-settings-page__btn--danger"
            onClick={() =>
              openModal(t('pages.superAdminSettings.danger.maintenance'), t('pages.superAdminSettings.danger.maintenanceBody'), () => {
                patch('dangerFlags', { maintenanceMode: true });
                toast.success(tr('toasts.dangerDone'));
              })
            }
          >
            {t('pages.superAdminSettings.danger.maintenance')}
          </button>
        </div>
        {(settings.dangerFlags.registrationsDisabled || settings.dangerFlags.maintenanceMode) && (
          <p className="super-admin-settings-page__card-lead" style={{ marginTop: '0.75rem', color: '#922b21' }}>
            Demo: {settings.dangerFlags.registrationsDisabled ? `${t('pages.superAdminSettings.danger.disableReg')} · ` : ''}
            {settings.dangerFlags.maintenanceMode ? t('pages.superAdminSettings.danger.maintenance') : ''}
          </p>
        )}
      </>,
      true
    );

  const renderSection = () => {
    switch (activeSection) {
      case 'platform':
        return renderPlatform();
      case 'registration':
        return renderRegistration();
      case 'subscription':
        return renderSubscription();
      case 'access':
        return renderAccess();
      case 'notifications':
        return renderNotifications();
      case 'reports':
        return renderReports();
      case 'localization':
        return renderLocalization();
      case 'audit':
        return renderAudit();
      case 'backup':
        return renderBackup();
      case 'danger':
        return renderDanger();
      default:
        return null;
    }
  };

  return (
    <div className="super-admin-settings-page" dir={pageRtl ? 'rtl' : 'ltr'}>
      <header className="super-admin-settings-page__header">
        <h1 className="super-admin-settings-page__title">{t('pages.superAdminSettings.title')}</h1>
        <p className="super-admin-settings-page__subtitle">{t('pages.superAdminSettings.subtitle')}</p>
      </header>

      <div className="super-admin-settings-page__shell">
        <nav className="super-admin-settings-page__nav" aria-label={t('pages.superAdminSettings.title')}>
          {NAV.map(({ id, icon: Icon }) => (
            <button
              key={id}
              type="button"
              className={`super-admin-settings-page__nav-btn${activeSection === id ? ' is-active' : ''}`}
              onClick={() => setActiveSection(id)}
            >
              <Icon className="super-admin-settings-page__nav-icon" size={16} aria-hidden />
              {t(`pages.superAdminSettings.nav.${id}`)}
            </button>
          ))}
        </nav>

        <div className="super-admin-settings-page__main">
          <div className="super-admin-settings-page__toolbar">
            <button type="button" className="super-admin-settings-page__btn super-admin-settings-page__btn--ghost" onClick={handleReset}>
              <Undo2 size={16} aria-hidden />
              {t('pages.superAdminSettings.reset')}
            </button>
            <button type="button" className="super-admin-settings-page__btn super-admin-settings-page__btn--gold" onClick={handleSave}>
              <Save size={16} aria-hidden />
              {t('pages.superAdminSettings.save')}
            </button>
          </div>
          {renderSection()}
        </div>
      </div>

      <ConfirmModal
        open={modal.open}
        title={modal.title}
        description={modal.description}
        onClose={closeModal}
        onConfirm={modal.onConfirm}
        confirmLabel={t('pages.superAdminSettings.modal.confirm')}
        cancelLabel={t('pages.superAdminSettings.modal.cancel')}
      />
    </div>
  );
}
