/**
 * EquiCore report PDF utilities — jsPDF + autotable (LTR/RTL) and html2canvas preview export.
 */
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import html2canvas from 'html2canvas';

const NAVY = [21, 36, 71];
const GOLD = [201, 162, 39];
const MUTED = [92, 101, 122];

function safeFilename(title) {
  return String(title || 'report').replace(/[^\w\u0600-\u06FF\s-]/g, '').trim().replace(/\s+/g, '-') || 'report';
}

function drawHeader(doc, { reportTitle, stableName, isRtl, labels }) {
  const pageW = doc.internal.pageSize.getWidth();
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageW, 32, 'F');
  doc.setFillColor(...GOLD);
  doc.rect(0, 32, pageW, 1.2, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('EquiCore', isRtl ? pageW - 14 : 14, 14, { align: isRtl ? 'right' : 'left' });

  doc.setFontSize(15);
  doc.text(reportTitle, isRtl ? pageW - 14 : 14, 24, { align: isRtl ? 'right' : 'left', maxWidth: pageW - 28 });

  doc.setTextColor(...MUTED);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const metaY = 42;
  const x = isRtl ? pageW - 14 : 14;
  const align = isRtl ? 'right' : 'left';
  doc.text(`${labels.stable}: ${stableName}`, x, metaY, { align });
  if (labels.generatedBy) doc.text(`${labels.generatedBy}: ${labels.generatedByValue}`, x, metaY + 5, { align });
  if (labels.generatedAt) doc.text(`${labels.generatedAt}: ${labels.generatedAtValue}`, x, metaY + 10, { align });
  if (labels.dateRange) doc.text(`${labels.dateRange}: ${labels.dateRangeValue}`, x, metaY + 15, { align });

  return metaY + 22;
}

function drawSummary(doc, startY, summary, isRtl, labels) {
  if (!summary?.length) return startY;
  const pageW = doc.internal.pageSize.getWidth();
  const x = isRtl ? pageW - 14 : 14;
  const align = isRtl ? 'right' : 'left';

  doc.setTextColor(...NAVY);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(labels.summary || 'Summary', x, startY, { align });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(40, 40, 40);
  let y = startY + 6;
  summary.forEach((row) => {
    doc.text(`${row.label}: ${row.value}`, x, y, { align, maxWidth: pageW - 28 });
    y += 5;
  });
  return y + 4;
}

function drawFooter(doc, labels) {
  const pageCount = doc.internal.getNumberOfPages();
  const pageW = doc.internal.pageSize.getWidth();
  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(
      `${labels.footer || 'Generated by EquiCore'} · ${i} / ${pageCount}`,
      pageW / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: 'center' }
    );
  }
}

/**
 * Generate A4 PDF with navy header, gold accent, autotable body (EN LTR / AR RTL).
 */
export function generateReportPDF({
  reportTitle,
  language = 'en',
  stableName,
  generatedBy,
  generatedAt,
  dateRange,
  summary = [],
  tableColumns = [],
  tableRows = [],
  notes = '',
  includeSignature = false,
  labels = {},
}) {
  const isRtl = language === 'ar';
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const defaultLabels = {
    stable: isRtl ? 'الإسطبل' : 'Stable',
    generatedBy: isRtl ? 'أُعد بواسطة' : 'Generated by',
    generatedByValue: generatedBy || '—',
    generatedAt: isRtl ? 'تاريخ الإنشاء' : 'Generated at',
    generatedAtValue: generatedAt || new Date().toLocaleString(isRtl ? 'ar-BH' : 'en-GB'),
    dateRange: isRtl ? 'الفترة' : 'Date range',
    dateRangeValue: dateRange || '—',
    summary: isRtl ? 'ملخص' : 'Summary',
    notes: isRtl ? 'ملاحظات' : 'Notes',
    signature: isRtl ? 'التوقيع' : 'Signature',
    footer: isRtl ? 'أُنشئ بواسطة EquiCore' : 'Generated by EquiCore',
    ...labels,
  };

  let cursorY = drawHeader(doc, { reportTitle, stableName, isRtl, labels: defaultLabels });
  cursorY = drawSummary(doc, cursorY, summary, isRtl, defaultLabels);

  if (tableColumns.length && tableRows.length) {
    autoTable(doc, {
      startY: cursorY,
      head: [tableColumns],
      body: tableRows,
      styles: {
        font: 'helvetica',
        fontSize: 8,
        cellPadding: 2.5,
        halign: isRtl ? 'right' : 'left',
        valign: 'middle',
      },
      headStyles: {
        fillColor: NAVY,
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        halign: isRtl ? 'right' : 'left',
      },
      alternateRowStyles: { fillColor: [248, 249, 252] },
      margin: { left: 14, right: 14 },
      theme: 'striped',
    });
    cursorY = doc.lastAutoTable.finalY + 8;
  }

  const pageW = doc.internal.pageSize.getWidth();
  const x = isRtl ? pageW - 14 : 14;
  const align = isRtl ? 'right' : 'left';

  if (notes) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...NAVY);
    doc.text(defaultLabels.notes, x, cursorY, { align });
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(50, 50, 50);
    const split = doc.splitTextToSize(notes, pageW - 28);
    doc.text(split, x, cursorY + 6, { align });
    cursorY += 6 + split.length * 4.5;
  }

  if (includeSignature) {
    cursorY += 10;
    doc.setDrawColor(...GOLD);
    doc.line(isRtl ? pageW - 80 : 14, cursorY, isRtl ? pageW - 14 : 94, cursorY);
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(defaultLabels.signature, x, cursorY + 5, { align });
  }

  drawFooter(doc, defaultLabels);
  doc.save(`${safeFilename(reportTitle)}.pdf`);
  return doc;
}

/**
 * Export the on-screen HTML preview (best for Arabic typography / RTL).
 */
export async function generateReportPDFFromPreview(element, { reportTitle, language = 'en' } = {}) {
  if (!element) throw new Error('Preview element required');
  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    backgroundColor: '#ffffff',
    logging: false,
  });
  const imgData = canvas.toDataURL('image/png');
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const imgH = (canvas.height * pageW) / canvas.width;
  let heightLeft = imgH;
  let position = 0;

  pdf.addImage(imgData, 'PNG', 0, position, pageW, imgH);
  heightLeft -= pageH;

  while (heightLeft > 0) {
    position = heightLeft - imgH;
    pdf.addPage();
    pdf.addImage(imgData, 'PNG', 0, position, pageW, imgH);
    heightLeft -= pageH;
  }

  const footer = language === 'ar' ? 'أُنشئ بواسطة EquiCore' : 'Generated by EquiCore';
  const total = pdf.internal.getNumberOfPages();
  for (let i = 1; i <= total; i += 1) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(...MUTED);
    pdf.text(`${footer} · ${i} / ${total}`, pageW / 2, pageH - 6, { align: 'center' });
  }

  pdf.save(`${safeFilename(reportTitle)}.pdf`);
  return pdf;
}

export function printReportPreview() {
  window.print();
}
