/** Dummy data for Training Schedule (frontend-only; backend-ready shape). */

import { groupAssignment, singleAssignment } from './scheduleEventDefaults';

export const SCHEDULE_HORSES = [
  { id: 'horse_001', name: 'Thunder' },
  { id: 'horse_002', name: 'Desert Pearl' },
  { id: 'horse_003', name: 'Royal Flame' },
  { id: 'horse_004', name: 'Silver Arrow' },
];

export const SCHEDULE_RIDERS = [
  { id: 'rider_001', name: 'Ahmed Al-Mansoori' },
  { id: 'rider_002', name: 'Khalid Hassan' },
  { id: 'rider_003', name: 'Sara Al-Khalifa' },
  { id: 'rider_004', name: 'Mohammed Al-Salem' },
];

export const SCHEDULE_TRAINERS = [
  { id: 'trainer_001', name: 'Ali Hussein Salman' },
  { id: 'trainer_002', name: 'Omar Al-Nuaimi' },
];

export const TRAINING_LIBRARY_TEMPLATES = [
  {
    id: 'template_001',
    name: 'Endurance Base Conditioning',
    discipline: 'Endurance',
    category: 'Aerobic base',
    difficultyLevel: 'Intermediate',
    estimatedDistance: '18 km',
    estimatedDuration: '1h 30m',
    targetAverageSpeed: '12 km/h',
    goal: 'Build aerobic capacity without overloading tendons.',
    warmUp: '15 min active walk, 10 min trot on soft track.',
    mainExercise: '45 min steady canter in heart-rate zone 2; monitor hydration.',
    coolDown: '20 min walk, leg stretch, check tendons.',
    healthPrecautions: 'Avoid hard ground if hoof sensitivity noted.',
  },
  {
    id: 'template_002',
    name: 'Recovery Walk',
    discipline: 'General',
    category: 'Recovery',
    difficultyLevel: 'Light',
    estimatedDistance: '5 km',
    estimatedDuration: '45m',
    targetAverageSpeed: '6 km/h',
    goal: 'Promote circulation and mental relaxation.',
    warmUp: '5 min loose rein walk from stable.',
    mainExercise: '30 min relaxed walk on varied terrain.',
    coolDown: '10 min grooming and cool hose if warm.',
    healthPrecautions: 'Stop if any lameness appears.',
  },
  {
    id: 'template_003',
    name: 'Speed Work',
    discipline: 'Endurance',
    category: 'Speed',
    difficultyLevel: 'Advanced',
    estimatedDistance: '12 km',
    estimatedDuration: '1h',
    targetAverageSpeed: '16 km/h',
    goal: 'Short controlled speed intervals.',
    warmUp: '20 min progressive trot.',
    mainExercise: '4 × 3 min canter at 18 km/h with 3 min walk between.',
    coolDown: '15 min walk and pulse check.',
    healthPrecautions: 'Requires vet clearance after recent competition.',
  },
  {
    id: 'template_004',
    name: 'Hill Training',
    discipline: 'Endurance',
    category: 'Strength',
    difficultyLevel: 'Intermediate',
    estimatedDistance: '10 km',
    estimatedDuration: '1h 15m',
    targetAverageSpeed: '10 km/h',
    goal: 'Develop hindquarter strength on inclines.',
    warmUp: '15 min flat trot.',
    mainExercise: '6 hill repeats at controlled pace; walk descent.',
    coolDown: '20 min flat walk.',
    healthPrecautions: 'Check footing; avoid deep sand on hot days.',
  },
  {
    id: 'template_005',
    name: 'Jumping Grid',
    discipline: 'Show Jumping',
    category: 'Technical',
    difficultyLevel: 'Intermediate',
    estimatedDistance: '—',
    estimatedDuration: '50m',
    targetAverageSpeed: '—',
    goal: 'Rhythm and accuracy over a grid.',
    warmUp: 'Flat work 15 min, poles on ground.',
    mainExercise: 'Grid of 4 fences, 6–8 repetitions with rest.',
    coolDown: '10 min walk, stretch.',
    healthPrecautions: 'Inspect legs before and after session.',
  },
  {
    id: 'template_006',
    name: 'Flat Work',
    discipline: 'Dressage',
    category: 'Flat',
    difficultyLevel: 'Light',
    estimatedDistance: '—',
    estimatedDuration: '45m',
    targetAverageSpeed: '—',
    goal: 'Suppleness, contact, and lateral work.',
    warmUp: '10 min walk, 10 min trot circles.',
    mainExercise: 'Shoulder-in, haunches-in, lengthenings.',
    coolDown: '10 min stretch walk.',
    healthPrecautions: 'Adjust intensity for young horses.',
  },
];

let eventCounter = 13;

export function nextEventId() {
  eventCounter += 1;
  return `event_${String(eventCounter).padStart(3, '0')}`;
}

export function buildInitialScheduleEvents() {
  return [
    {
      id: 'event_001',
      stableId: 'stable_001',
      eventType: 'Training',
      status: 'Sent to Rider',
      title: 'Endurance Base Conditioning',
      trainingTemplateId: 'template_001',
      trainerId: 'trainer_001',
      trainerName: 'Ali Hussein Salman',
      ...singleAssignment('horse_001', 'Thunder', 'rider_001', 'Ahmed Al-Mansoori'),
      date: '2026-05-17',
      time: '06:00',
      duration: '1h 30m',
      location: '',
      notes: 'Morning endurance session',
      createdBy: 'Trainer',
      createdAt: '2026-05-16 18:30',
      sentAt: '2026-05-16 19:00',
      completedAt: null,
    },
    {
      id: 'event_002',
      stableId: 'stable_001',
      eventType: 'Training',
      status: 'Saved',
      title: 'Speed Work',
      trainingTemplateId: 'template_003',
      trainerId: 'trainer_002',
      trainerName: 'Omar Al-Nuaimi',
      ...singleAssignment('horse_002', 'Desert Pearl', 'rider_002', 'Khalid Hassan'),
      date: '2026-05-17',
      time: '16:30',
      duration: '1h',
      location: '',
      notes: 'Afternoon intervals — pending send',
      createdBy: 'Trainer',
      createdAt: '2026-05-16 14:00',
      sentAt: null,
      completedAt: null,
    },
    {
      id: 'event_003',
      stableId: 'stable_001',
      eventType: 'Competition',
      status: 'Saved',
      title: 'Bahrain Endurance Cup',
      trainingTemplateId: '',
      trainerId: 'trainer_001',
      trainerName: 'Ali Hussein Salman',
      ...singleAssignment('horse_003', 'Royal Flame', 'rider_003', 'Sara Al-Khalifa'),
      date: '2026-05-18',
      time: '05:00',
      duration: '4h',
      location: 'Sakhir',
      discipline: 'Endurance',
      notes: '80 km CEI1*',
      createdBy: 'Trainer',
      createdAt: '2026-05-10 09:00',
      sentAt: null,
      completedAt: null,
    },
    {
      id: 'event_004',
      stableId: 'stable_001',
      eventType: 'Race',
      status: 'Draft',
      title: 'Royal Stakes',
      trainingTemplateId: '',
      trainerId: 'trainer_002',
      trainerName: 'Omar Al-Nuaimi',
      ...singleAssignment('horse_004', 'Silver Arrow', 'rider_004', 'Mohammed Al-Salem'),
      date: '2026-05-19',
      time: '15:00',
      duration: '2m',
      location: 'Abu Dhabi',
      discipline: 'Flat',
      notes: '1600m handicap',
      createdBy: 'Trainer',
      createdAt: '2026-05-14 11:00',
      sentAt: null,
      completedAt: null,
    },
    {
      id: 'event_005',
      stableId: 'stable_001',
      eventType: 'Recovery',
      status: 'Saved',
      title: 'Post-competition recovery',
      trainingTemplateId: '',
      trainerId: 'trainer_001',
      trainerName: 'Ali Hussein Salman',
      ...singleAssignment('horse_001', 'Thunder'),
      date: '2026-05-20',
      time: '',
      duration: '3 days',
      location: '',
      recoveryEnd: '2026-05-22',
      reason: 'Tendon monitoring after long ride',
      notes: 'Hand walk only',
      createdBy: 'Trainer',
      createdAt: '2026-05-18 08:00',
      sentAt: null,
      completedAt: null,
    },
    {
      id: 'event_006',
      stableId: 'stable_001',
      eventType: 'Vet Check',
      status: 'Completed',
      title: 'Routine lameness screening',
      trainingTemplateId: '',
      trainerId: 'trainer_001',
      trainerName: 'Ali Hussein Salman',
      ...singleAssignment('horse_002', 'Desert Pearl'),
      date: '2026-05-15',
      time: '10:00',
      duration: '30m',
      location: 'Stable clinic',
      vetName: 'Dr. Fatima Al-Zaabi',
      reason: 'Pre-season clearance',
      notes: 'Cleared for training',
      createdBy: 'Trainer',
      createdAt: '2026-05-12 16:00',
      sentAt: null,
      completedAt: '2026-05-15 11:00',
    },
    {
      id: 'event_007',
      stableId: 'stable_001',
      eventType: 'Training',
      status: 'Completed',
      title: 'Hill Training',
      trainingTemplateId: 'template_004',
      trainerId: 'trainer_001',
      trainerName: 'Ali Hussein Salman',
      ...singleAssignment('horse_003', 'Royal Flame', 'rider_001', 'Ahmed Al-Mansoori'),
      date: '2026-05-14',
      time: '07:00',
      duration: '1h 15m',
      location: '',
      notes: 'Completed successfully',
      createdBy: 'Trainer',
      createdAt: '2026-05-13 12:00',
      sentAt: '2026-05-13 18:00',
      completedAt: '2026-05-14 08:30',
    },
    {
      id: 'event_008',
      stableId: 'stable_001',
      eventType: 'Training',
      status: 'Sent to Rider',
      title: 'Flat Work',
      trainingTemplateId: 'template_006',
      trainerId: 'trainer_002',
      trainerName: 'Omar Al-Nuaimi',
      ...groupAssignment({
        horseIds: ['horse_003', 'horse_004'],
        horses: ['Royal Flame', 'Silver Arrow'],
        riderIds: ['rider_003', 'rider_004'],
        riders: ['Sara Al-Khalifa', 'Mohammed Al-Salem'],
        groupName: 'Young riders group',
        groupNotes: 'Arena flat work — group session',
      }),
      date: '2026-05-16',
      time: '09:00',
      duration: '45m',
      location: 'Indoor arena',
      notes: 'Focus on contact',
      createdBy: 'Trainer',
      createdAt: '2026-05-15 10:00',
      sentAt: '2026-05-15 10:30',
      completedAt: null,
    },
    {
      id: 'event_009',
      stableId: 'stable_001',
      eventType: 'Training',
      status: 'Saved',
      title: 'Jumping Grid',
      trainingTemplateId: 'template_005',
      trainerId: 'trainer_002',
      trainerName: 'Omar Al-Nuaimi',
      ...singleAssignment('horse_002', 'Desert Pearl', 'rider_004', 'Mohammed Al-Salem'),
      date: '2026-05-21',
      time: '11:00',
      duration: '50m',
      location: 'Outdoor arena',
      notes: '',
      createdBy: 'Trainer',
      createdAt: '2026-05-17 09:00',
      sentAt: null,
      completedAt: null,
    },
    {
      id: 'event_010',
      stableId: 'stable_001',
      eventType: 'Recovery',
      status: 'Saved',
      title: 'Soft tissue rest',
      trainingTemplateId: '',
      trainerId: 'trainer_002',
      trainerName: 'Omar Al-Nuaimi',
      ...singleAssignment('horse_004', 'Silver Arrow'),
      date: '2026-05-17',
      time: '',
      duration: '2 days',
      location: '',
      recoveryEnd: '2026-05-18',
      reason: 'Minor strain',
      notes: 'Stall rest + ice',
      createdBy: 'Trainer',
      createdAt: '2026-05-16 20:00',
      sentAt: null,
      completedAt: null,
    },
    {
      id: 'event_011',
      stableId: 'stable_001',
      eventType: 'Competition',
      status: 'Cancelled',
      title: 'Regional Show Jumping',
      trainingTemplateId: '',
      trainerId: 'trainer_001',
      trainerName: 'Ali Hussein Salman',
      ...singleAssignment('horse_001', 'Thunder', 'rider_002', 'Khalid Hassan'),
      date: '2026-05-22',
      time: '14:00',
      duration: '2h',
      location: 'Dubai',
      discipline: 'Show Jumping',
      notes: 'Withdrawn — transport issue',
      createdBy: 'Trainer',
      createdAt: '2026-05-01 08:00',
      sentAt: null,
      completedAt: null,
    },
    {
      id: 'event_012',
      stableId: 'stable_001',
      eventType: 'Training',
      status: 'Draft',
      title: 'Recovery Walk',
      trainingTemplateId: 'template_002',
      trainerId: 'trainer_001',
      trainerName: 'Ali Hussein Salman',
      ...singleAssignment('horse_003', 'Royal Flame', 'rider_002', 'Khalid Hassan'),
      date: '2026-05-23',
      time: '08:00',
      duration: '45m',
      location: '',
      notes: 'Light session',
      createdBy: 'Trainer',
      createdAt: '2026-05-17 07:00',
      sentAt: null,
      completedAt: null,
    },
    {
      id: 'event_013',
      stableId: 'stable_001',
      eventType: 'Training',
      status: 'Saved',
      title: 'Endurance Base Conditioning',
      trainingTemplateId: 'template_001',
      trainerId: 'trainer_001',
      trainerName: 'Ali Hussein Salman',
      ...groupAssignment({
        horseIds: ['horse_001', 'horse_002'],
        horses: ['Thunder', 'Desert Pearl'],
        riderIds: ['rider_001', 'rider_002'],
        riders: ['Ahmed Al-Mansoori', 'Khalid Hassan'],
        groupName: 'Morning Endurance Group',
        groupNotes: 'Shared warm-up and cool-down; staggered departures',
      }),
      date: '2026-05-17',
      time: '07:30',
      duration: '1h 30m',
      location: 'Desert track',
      notes: 'Group endurance base session',
      createdBy: 'Trainer',
      createdAt: '2026-05-16 12:00',
      sentAt: null,
      completedAt: null,
    },
  ];
}

export const EVENT_TYPES = ['Training', 'Competition', 'Race', 'Recovery', 'Vet Check'];
export const EVENT_STATUSES = ['Draft', 'Saved', 'Sent to Rider', 'Completed', 'Cancelled'];

/** i18n-safe keys (values with spaces break dot-notation lookups). */
export const EVENT_TYPE_I18N = {
  Training: 'training',
  Competition: 'competition',
  Race: 'race',
  Recovery: 'recovery',
  'Vet Check': 'vetCheck',
};

export const STATUS_I18N = {
  Draft: 'draft',
  Saved: 'saved',
  'Sent to Rider': 'sentToRider',
  Completed: 'completed',
  Cancelled: 'cancelled',
};

export const DIFFICULTY_I18N = {
  Light: 'light',
  Intermediate: 'intermediate',
  Advanced: 'advanced',
};

export const DISCIPLINE_I18N = {
  Endurance: 'endurance',
  General: 'general',
  'Show Jumping': 'showJumping',
  Dressage: 'dressage',
};

export const CREATED_BY_I18N = {
  Trainer: 'trainer',
};

export function eventTypeClass(eventType) {
  const map = {
    Training: 'training',
    Competition: 'competition',
    Race: 'race',
    Recovery: 'recovery',
    'Vet Check': 'vet',
  };
  return map[eventType] || 'training';
}

export function statusClass(status) {
  return status.replace(/\s+/g, '-').toLowerCase();
}
